# Database credentials Secret
# NOTE: In production, use AWS Secrets Manager or Kubernetes External Secrets
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
stringData:
  DB_HOST: "ecommerce-mysql.cdcwuiog4ivb.us-east-1.rds.amazonaws.com"
  DB_USER: "hamzachera"
  DB_PASSWORD: "Hamzaisgood44**"
